# 开发环境配置
app:
  name: "Server Manager"
  version: "0.1.0"
  mode: "development"
  port: 8080
  host: "0.0.0.0"

# 数据库配置
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "servermanager"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "300s"

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

# JWT配置
jwt:
  secret: "your-super-secret-jwt-key-change-in-production"
  expire_hours: 24

# 日志配置
log:
  level: "debug"
  format: "json"
  output: "stdout"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days

# CORS配置
cors:
  allow_origins:
    - "http://localhost:5173"  # Vite dev server
    - "http://localhost:3000"  # Alternative frontend port
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"

# 文件上传配置
upload:
  max_size: "10MB"
  allowed_types:
    - "text/yaml"
    - "text/plain"
    - "application/x-yaml"

# Ansible配置
ansible:
  config_path: "/etc/ansible"
  inventory_dir: "./data/inventories"
  playbook_dir: "./data/playbooks"
  log_dir: "./logs/ansible"
  timeout: 300 # 秒